### ISSUE TITLE
밋업 참가자 녹취 파일 제공 문의 (기록 누락/오류 보충 목적)

### ISSUE THREAD

**Issue by combacsa** [innovationacademy-kr/meetup-logs#1]
안녕하세요? 밋업 참가자 변규홍입니다. 훌륭한 밋업 결과 정리 감사드리구요. 몇 가지 발언내용에 잘못 속기된 부분이 있는 듯하여, 풀리퀘를 넣으려고 합니다.

정확한 수정을 위해, 가능하다면 녹취파일을 전달받았으면 하는데요. 참가신청 시 제출한 메일주소로 녹취음원을 전달받을 수 있을까요? 

보안상 문제 등으로 어렵다면 제가 특정 장소로 가서 직접 청취하는 방법도 고려하고 있습니다. 

고맙습니다.

**Comment by hnlee1234** [comment]
참가신청 때 제출하신 메일주소로 녹취록 보냈습니다.
